name = "hackernews"

account_id = "bec77b03b1fb3338a921fd1c11a97aaa"
compatibility_date = "2022-08-04"
main = "./.output/server/index.mjs"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = ".output/public"